import { Fighter } from './types';

export const fighters: Fighter[] = [
  {
    id: 'kodiak',
    name: 'Kodiak',
    animal: 'Bear',
    image: '/fighters/kodiak.jpg',
    backstory: 'Born in the frozen wastelands of Alaska, Kodiak spent years wrestling grizzlies before entering the arena. His devastating power has ended more fights in the first round than any other competitor. They don\'t call him "The Mountain" for nothing.',
    catchphrase: 'I don\'t need speed. One hit is all it takes.',
    color: '#8B4513',
    hp: 100,
    wins: 14,
    losses: 3,
    kos: 11,
    damageDealt: 4280,
    moves: [
      { name: 'Heavy Swipe', minDamage: 12, maxDamage: 22 },
      { name: 'Bear Hug', minDamage: 10, maxDamage: 18 },
      { name: 'Skull Crush', minDamage: 15, maxDamage: 25 },
      { name: 'Ground Slam', minDamage: 8, maxDamage: 20 },
      { name: 'Maul', minDamage: 14, maxDamage: 24 },
    ],
    specialTrait: { name: 'Heavy Hands', description: '+10% damage on final blow' },
    focalPoint: 'center 15%',
  },
  {
    id: 'fang',
    name: 'Fang',
    animal: 'Wolf',
    image: '/fighters/fang.jpg',
    backstory: 'The lone wolf who left his pack to prove he could dominate alone. Fang\'s calculated fighting style and cold precision make him one of the most consistent fighters in the league. Every move has purpose, every strike draws blood.',
    catchphrase: 'The pack taught me patience. The arena taught me to kill.',
    color: '#708090',
    hp: 100,
    wins: 12,
    losses: 4,
    kos: 8,
    damageDealt: 3750,
    moves: [
      { name: 'Fang Strike', minDamage: 10, maxDamage: 18 },
      { name: 'Lunge Bite', minDamage: 12, maxDamage: 20 },
      { name: 'Pack Fury', minDamage: 8, maxDamage: 16 },
      { name: 'Throat Rip', minDamage: 14, maxDamage: 22 },
      { name: 'Shadow Dash', minDamage: 9, maxDamage: 17 },
    ],
    specialTrait: { name: 'Pack Instinct', description: '+5% damage when HP > 50%' },
    focalPoint: 'center 15%',
  },
  {
    id: 'talon',
    name: 'Talon',
    animal: 'Eagle',
    image: '/fighters/talon.jpg',
    backstory: 'King of the skies turned king of the cage. Talon\'s blinding speed and aerial strikes leave opponents swinging at air. His arrogance is matched only by his highlight reel of devastating knockouts from angles nobody sees coming.',
    catchphrase: 'You can\'t hit what you can\'t see.',
    color: '#DAA520',
    hp: 100,
    wins: 11,
    losses: 5,
    kos: 7,
    damageDealt: 3420,
    moves: [
      { name: 'Talon Slash', minDamage: 8, maxDamage: 16 },
      { name: 'Dive Bomb', minDamage: 14, maxDamage: 22 },
      { name: 'Wing Buffet', minDamage: 6, maxDamage: 14 },
      { name: 'Sky Strike', minDamage: 10, maxDamage: 20 },
      { name: 'Raptor Fury', minDamage: 12, maxDamage: 18 },
    ],
    specialTrait: { name: 'Aerial Dodge', description: '5% base dodge chance' },
    focalPoint: 'center 28%',
  },
  {
    id: 'jaws',
    name: 'Jaws',
    animal: 'Crocodile',
    image: '/fighters/jaws.jpg',
    backstory: 'Ancient and patient, Jaws has been waiting in the murky depths for 200 million years of evolution. His death roll technique has never been escaped. When he locks on, the fight is already over — his opponents just don\'t know it yet.',
    catchphrase: 'I\'ve been killing since before your species existed.',
    color: '#2E8B57',
    hp: 100,
    wins: 10,
    losses: 5,
    kos: 9,
    damageDealt: 3680,
    moves: [
      { name: 'Death Roll', minDamage: 14, maxDamage: 24 },
      { name: 'Tail Whip', minDamage: 8, maxDamage: 16 },
      { name: 'Jaw Clamp', minDamage: 12, maxDamage: 20 },
      { name: 'Ambush Strike', minDamage: 10, maxDamage: 18 },
      { name: 'Swamp Slam', minDamage: 11, maxDamage: 19 },
    ],
    specialTrait: { name: 'Death Roll', description: 'If attack crits, opponent skips next turn' },
    focalPoint: 'center 25%',
  },
  {
    id: 'mane',
    name: 'Mane',
    animal: 'Lion',
    image: '/fighters/mane.jpg',
    backstory: 'The self-proclaimed King of the Arena, Mane fights like royalty with nothing to prove and everything to defend. His aggressive all-out offense overwhelms opponents before they can find their rhythm. The crowd lives and dies with every roar.',
    catchphrase: 'Bow before the king, or be broken by him.',
    color: '#FFD700',
    hp: 100,
    wins: 13,
    losses: 4,
    kos: 10,
    damageDealt: 4100,
    moves: [
      { name: 'Royal Strike', minDamage: 12, maxDamage: 22 },
      { name: 'Lion\'s Roar', minDamage: 10, maxDamage: 18 },
      { name: 'Pride Fury', minDamage: 14, maxDamage: 24 },
      { name: 'Mane Whip', minDamage: 8, maxDamage: 16 },
      { name: 'King\'s Judgment', minDamage: 13, maxDamage: 21 },
    ],
    specialTrait: { name: "King's Roar", description: 'First attack of fight guaranteed +15% damage' },
    focalPoint: 'center 10%',
  },
  {
    id: 'venom',
    name: 'Venom',
    animal: 'Snake',
    image: '/fighters/venom.jpg',
    backstory: 'Slithering out of the darkest jungles, Venom fights with patience and poison. Every strike injects toxins that slowly drain the life from opponents. By the time they realize what\'s happening, their muscles have already betrayed them.',
    catchphrase: 'The bite is just the beginning. The venom does the rest.',
    color: '#9400D3',
    hp: 100,
    wins: 9,
    losses: 6,
    kos: 5,
    damageDealt: 3200,
    moves: [
      { name: 'Venom Strike', minDamage: 8, maxDamage: 16 },
      { name: 'Coil Crush', minDamage: 10, maxDamage: 18 },
      { name: 'Toxic Fang', minDamage: 12, maxDamage: 20 },
      { name: 'Serpent Lash', minDamage: 9, maxDamage: 17 },
      { name: 'Poison Spit', minDamage: 6, maxDamage: 14 },
    ],
    specialTrait: { name: 'Poison', description: 'Each hit applies 2 HP/turn poison for 2 turns' },
    focalPoint: 'center 12%',
  },
  {
    id: 'kong',
    name: 'Kong',
    animal: 'Gorilla',
    image: '/fighters/kong.jpg',
    backstory: 'The silent destroyer. Kong doesn\'t trash talk — he lets his fists deliver the message. Raised in the depths of the Congo, his raw power is unmatched. When Kong connects with a clean shot, fighters don\'t get back up. Simple as that.',
    catchphrase: '...',
    color: '#333333',
    hp: 100,
    wins: 11,
    losses: 4,
    kos: 10,
    damageDealt: 3950,
    moves: [
      { name: 'Ground Pound', minDamage: 14, maxDamage: 24 },
      { name: 'Chest Beat', minDamage: 8, maxDamage: 16 },
      { name: 'Gorilla Press', minDamage: 12, maxDamage: 22 },
      { name: 'Primal Smash', minDamage: 10, maxDamage: 20 },
      { name: 'Kong Crush', minDamage: 15, maxDamage: 25 },
    ],
    specialTrait: { name: 'Berserker', description: '+10% damage when HP < 30%' },
    focalPoint: 'center 18%',
  },
  {
    id: 'razor',
    name: 'Razor',
    animal: 'Shark',
    image: '/fighters/razor.jpg',
    backstory: 'From the deepest trenches of the Pacific, Razor is relentless. Once he smells weakness, he enters a blood frenzy that makes him increasingly dangerous. Every fight is a ticking time bomb — the longer it goes, the more lethal Razor becomes.',
    catchphrase: 'Blood in the water. My favorite smell.',
    color: '#4682B4',
    hp: 100,
    wins: 10,
    losses: 6,
    kos: 8,
    damageDealt: 3580,
    moves: [
      { name: 'Razor Bite', minDamage: 10, maxDamage: 20 },
      { name: 'Fin Slash', minDamage: 8, maxDamage: 16 },
      { name: 'Blood Frenzy', minDamage: 14, maxDamage: 24 },
      { name: 'Deep Strike', minDamage: 12, maxDamage: 22 },
      { name: 'Jaws of Death', minDamage: 11, maxDamage: 19 },
    ],
    specialTrait: { name: 'Blood Frenzy', description: '+3% damage for each 10% HP opponent has lost' },
    focalPoint: 'center 5%',
  },
];

export function getFighter(id: string): Fighter | undefined {
  return fighters.find((f) => f.id === id);
}
